from __future__ import annotations

import math

from core.sizing_math import (
    calc_bs_real,
    calc_Cmodel,
    calc_FPS,
    calc_Kbatch,
    calc_Ssim,
    calc_T,
    calc_e2e_latency,
    calc_e2e_latency_load,
    calc_generation_time,
    calc_gpus_per_instance,
    calc_instances_per_server,
    calc_instances_per_server_tp,
    calc_kv_free_per_instance_gb,
    calc_kv_mla,
    calc_kv_per_session_gb,
    calc_model_mem_gb,
    calc_p_effective,
    calc_servers_by_compute,
    calc_servers_by_memory,
    calc_sessions_per_server,
    calc_th_decode_analyt,
    calc_th_decode_mem,
    calc_th_prefill_analyt,
    calc_th_prefill_cb_compute,
    calc_th_prefill_cb_mem,
    calc_th_server_comp,
    calc_th_server_dec,
    calc_th_server_pf,
    calc_ttft,
    select_th_decode,
    select_th_prefill,
)
from core.workload import calc_d_attn, normalize_context
from errors import ValidationAppError
from models import SizingInput, SizingOutput
from services.gpu_catalog_service import (
    lookup_gpu_bandwidth_gbs,
    lookup_gpu_price_usd,
    lookup_gpu_tflops,
)


def run_sizing(inp: SizingInput) -> SizingOutput:
    """
    Main sizing pipeline — Methodology v2.

    Sizing runs under two independent constraints:
    - GPU memory (sections 3-5)
    - compute throughput (section 6)
    Final: max(servers_by_memory, servers_by_compute)
    """

    # ── Section 2.1: Ssim — peak concurrent sessions ──
    Ssim = calc_Ssim(
        inp.internal_users,
        inp.penetration_internal,
        inp.concurrency_internal,
        inp.external_users,
        inp.penetration_external,
        inp.concurrency_external,
        inp.sessions_per_user_J,
    )
    # Прил. В.4.3: параллельные ветви одного запроса учитываются как сессии
    # (память и batch); K_calls остаётся числом последовательных вызовов.
    Ssim = Ssim * inp.parallel_branches_P

    # ── Section 2.2: T — total request+response length in tokens ──
    T = calc_T(
        inp.system_prompt_tokens_SP,
        inp.user_prompt_tokens_Prp,
        inp.reasoning_tokens_MRT,
        inp.answer_tokens_A,
    )

    # ── Section 3.1: Mmodel — memory for model weights ──
    Mmodel = calc_model_mem_gb(
        inp.params_billions,
        inp.bytes_per_param,
        inp.emp_model,
        inp.safe_margin,
    )

    # ── Section 2.2 / Appendix В.3: context lengths (single source: core.workload) ──
    # SL_pf  — input of the last (longest) LLM call, window-limited;
    # T_dec  — tokens generated by one call (A + A_tool + MRT);
    # SL     — SL_pf + T_dec, used for the KV-cache;
    # SL_pf_eff — recomputed prefill tokens after the prefix cache.
    ctx = normalize_context(
        SP=inp.system_prompt_tokens_SP,
        Prp=inp.user_prompt_tokens_Prp,
        MRT=inp.reasoning_tokens_MRT,
        A=inp.answer_tokens_A,
        n_prp=inp.dialog_turns,
        ts_max=inp.max_context_window_TSmax,
        k_calls=inp.k_calls,
        sp_tools=inp.sp_tools,
        c_rag_static=inp.c_rag_static,
        c_rag_dynamic=inp.c_rag_dynamic,
        a_tool=inp.a_tool,
        reasoning_in_history=inp.reasoning_in_history,
        eta_cache=inp.eta_cache,
    )
    k_calls = ctx.k_calls
    TS = ctx.ts
    SL = ctx.sl
    SL_pf = ctx.sl_pf
    SL_pf_eff = ctx.sl_pf_eff
    Tdec = ctx.t_dec

    # §6.1: attention width (N_attn·d_head; MLA — separate prefill / decode widths)
    d_attn_pf, d_attn_dec = calc_d_attn(
        hidden_size=inp.hidden_size_H,
        num_attention_heads=inp.num_attention_heads,
        head_dim=inp.head_dim,
        kv_lora_rank=inp.kv_lora_rank,
        qk_rope_head_dim=inp.qk_rope_head_dim,
    )

    # ── Section 3.2: KV-cache per session ──
    # P5: branch on Multi-Head Latent Attention (MLA, DeepSeek-V2/V3/R1).
    # When kv_lora_rank > 0, the model uses MLA — different formula. For
    # standard MHA/GQA/MQA, fall back to the v2 formula and detect arch
    # from N_kv vs N_attention ratio.
    is_mla = bool(inp.kv_lora_rank and inp.kv_lora_rank > 0)
    if is_mla:
        MKV = calc_kv_mla(
            L=inp.layers_L,
            SL=SL,
            kv_lora_rank=int(inp.kv_lora_rank or 0),
            qk_rope_head_dim=int(inp.qk_rope_head_dim or 0),
            bytes_state=inp.bytes_per_kv_state,
            emp_kv=inp.emp_kv,
        )
        kv_arch_mode = "mla"
    else:
        MKV = calc_kv_per_session_gb(
            inp.layers_L,
            inp.hidden_size_H,
            SL,
            inp.bytes_per_kv_state,
            inp.emp_kv,
            inp.num_kv_heads,
            inp.num_attention_heads,
            head_dim=int(inp.head_dim) if inp.head_dim else None,
        )
        if inp.num_kv_heads == 1:
            kv_arch_mode = "mqa"
        elif inp.num_kv_heads < inp.num_attention_heads:
            kv_arch_mode = "gqa"
        else:
            kv_arch_mode = "mha"

    # ── Section 4.1: GPUs per model instance ──
    GPUcount_model = calc_gpus_per_instance(Mmodel, inp.gpu_mem_gb, inp.kavail)

    # ── Section 4.2: instances per server (no TP factor) ──
    Ncount_model = calc_instances_per_server(inp.gpus_per_server, GPUcount_model)

    # ── Section 4.3: free memory for KV at the base TP ──
    kv_free_base = calc_kv_free_per_instance_gb(
        GPUcount_model,
        inp.gpu_mem_gb,
        inp.kavail,
        Mmodel,
    )

    # ── Section 4.4: concurrent sessions and Kbatch ──
    # KV-cache sharding under TP — methodology §4.4 H-6:
    #   - MLA (DeepSeek V2/V3/R1): latent c_t^KV replicated on every TP rank,
    #     so per-instance session memory = M_KV · GPUcount_inst.
    #     S_TP = floor(kv_free_inst / (GPUcount_inst · M_KV))
    #   - MHA/GQA/MQA: K/V sharded by min(GPUcount_inst, N_kv) heads,
    #     remaining ranks replicate. Per-instance session memory =
    #     M_KV · GPUcount_inst / min(GPUcount_inst, N_kv).
    #     S_TP = floor(kv_free_inst · min(GPUcount_inst, N_kv) / (M_KV · GPUcount_inst))
    # When GPUcount_inst ≤ N_kv (typical) the standard form reduces to
    # floor(kv_free / M_KV) — matches the legacy calc_S_TP. The replication
    # penalty kicks in for high-TP configurations or low-N_kv models.

    def _s_tp(kv_free_gb: float, gpu_count_inst: int) -> int:
        if MKV <= 0 or gpu_count_inst <= 0:
            return 0
        if is_mla:
            # MLA: latent replicated unconditionally.
            denom = gpu_count_inst * MKV
            return int(kv_free_gb // denom) if denom > 0 else 0
        # Standard: shard by min(GPUcount_inst, N_kv).
        n_kv = max(1, int(inp.num_kv_heads))
        shard = min(gpu_count_inst, n_kv)
        return int((kv_free_gb * shard) // (MKV * gpu_count_inst))

    S_TP_base = _s_tp(kv_free_base, GPUcount_model)

    # Computation for Z × GPUcount_model GPUs (with the TP multiplier)
    Z = inp.tp_multiplier_Z
    GPUcount_z = Z * GPUcount_model
    kv_free_z = calc_kv_free_per_instance_gb(
        GPUcount_z,
        inp.gpu_mem_gb,
        inp.kavail,
        Mmodel,
    )
    S_TP_z = _s_tp(kv_free_z, GPUcount_z)

    Kbatch = calc_Kbatch(S_TP_z, S_TP_base, inp.saturation_coeff_C)

    # ── Section 5.1 (P11): Pipeline / Expert parallelism extends footprint ──
    # Total per-instance GPU count = TP × PP × EP (Appendix Г.7).
    # PP/EP > 1 reduces instances_per_server proportionally because each
    # instance now occupies more GPUs.
    pp_deg = int(inp.pp_degree or 1)
    ep_deg = int(inp.ep_degree or 1)
    eta_tp_used = float(inp.eta_tp if inp.eta_tp is not None else 1.0)
    Z_combined = Z * pp_deg * ep_deg
    NcountTP = calc_instances_per_server_tp(inp.gpus_per_server, GPUcount_model, Z_combined)
    Sserver = calc_sessions_per_server(NcountTP, S_TP_z)

    # ── Section 5.2: Servers by memory ──
    servers_mem = calc_servers_by_memory(Ssim, Sserver)
    if servers_mem is math.inf:
        raise ValidationAppError(
            "Невозможно разместить сессии по памяти. "
            "Увеличьте память GPU, уменьшите контекст или уменьшите KV/сессию."
        )

    # ── Section 6.1: Throughput per instance ──
    # P3 — MoE accounting: resolve P_active (for FPS, BS-independent).
    # P_effective is BS-dependent and lives in the §6.4 iteration loop.
    p_active = float(inp.params_active) if inp.params_active else float(inp.params_billions)
    is_moe_detailed = (
        inp.params_dense is not None
        and inp.params_moe is not None
        and inp.params_moe > 0
        and inp.n_experts is not None
        and inp.n_experts > 0
        and inp.k_experts is not None
        and inp.k_experts > 0
    )

    FPS = calc_FPS(p_active)

    # Determine Fcount_model — peak FLOPS per TP-model instance (methodology §6.1
    # row 70 "пиковая производительность GPU с учётом их количества на 1
    # экземпляр модели"). Per the xlsx (llm_calc/sizing.py:402) and the
    # reference Python implementation, this is `gpu_per_inst · flops_gpu`
    # where `gpu_per_inst = Z · GPUcount_model`. Earlier the web used
    # just `GPUcount_model` (per-instance pre-TP) — that understated
    # throughput by Z× for TP>1 deployments.
    gpu_tflops = inp.gpu_flops_Fcount
    if gpu_tflops is None:
        gpu_tflops = lookup_gpu_tflops(inp.gpu_id, inp.gpu_mem_gb)
    Fcount_model_flops = gpu_tflops * 1e12 * GPUcount_z if gpu_tflops > 0 else 0.0

    # Analytical throughput
    # P7: Engine mode determines prefill compute branch.
    #   - 'static' (offline / Triton w/o inflight): K_batch boost, uses SL.
    #   - 'continuous' (vLLM/SGLang/TGI default): K_batch=1, uses SL_pf_eff,
    #     and a separate mem-bound branch (computed inside iteration since
    #     it depends on BS_real and P_effective(BS_real+1)).
    engine_mode = inp.engine_mode or "continuous"

    # §6.1: Th_dec^analyt is the instance-level compute ceiling at BS = 1
    # (no K_batch); attention over the input context SL_pf plus half of the
    # generated tokens. Per-session value at BS_real = Th_dec^analyt / BS_real.
    th_dec_analyt = calc_th_decode_analyt(
        Fcount_model_flops,
        inp.eta_decode,
        1.0,
        FPS,
        inp.layers_L,
        d_attn_dec,
        SL_pf,
        Tdec,
    )

    # ── §Г (P11): Apply η_TP to nominal compute throughput branches ──
    # Communication overhead reduces effective throughput at TP > 1.
    # Default eta_tp_used=1.0 → no scaling. Scales the per-instance
    # compute branch for decode (th_dec_analyt). Prefill compute branch
    # (th_pf_compute_branch) is scaled later, after engine_mode resolves
    # the compute formula in §6.1 H-8/H-9.
    th_dec_analyt = th_dec_analyt * eta_tp_used

    # ── §6.1 H-7: Memory-bandwidth-bound decode (P1) — resolve bw_gpu ──
    bw_gpu = inp.bw_gpu_gbs
    if bw_gpu is None and inp.gpu_id:
        catalog_bw = lookup_gpu_bandwidth_gbs(inp.gpu_id)
        bw_gpu = catalog_bw if catalog_bw > 0 else None

    # ── §6.1 (P7): Prefill compute branch — BS-independent, computed once ──
    if engine_mode == "static":
        th_pf_compute_branch = calc_th_prefill_analyt(
            Fcount_model_flops,
            inp.eta_prefill,
            Kbatch,
            FPS,
            inp.layers_L,
            d_attn_pf,
            SL_pf,
        )
    else:
        # 'continuous' — K_batch = 1. Attention context is the full SL_pf
        # (cached prefix is still attended to); the prefix cache only reduces
        # the number of recomputed tokens SL_pf_eff used in C_model / TTFT.
        th_pf_compute_branch = calc_th_prefill_cb_compute(
            Fcount_model_flops,
            inp.eta_prefill,
            FPS,
            inp.layers_L,
            d_attn_pf,
            SL_pf,
        )
    # P11: η_TP scaling on prefill compute branch
    th_pf_compute_branch = th_pf_compute_branch * eta_tp_used

    # ── §6.4: Iterative servers-by-compute fixed point (methodology §6.4 Шаги 1–4) ──
    # Couples BS_real ↔ Servers. Both Th_pf(BS_real) and Th_dec(BS_real) are
    # recomputed at the same BS_real on every iteration. Stop on exact
    # Servers^(k+1) = Servers^(k); k_max = 20; status converged / oscillating /
    # not_converged. All published metrics are taken at the final state S*.
    MAX_ITER = 20
    effective_R = inp.rps_per_session_R * k_calls
    bw_value = bw_gpu if bw_gpu is not None else 0.0

    def _p_eff(bs: int) -> float:
        if is_moe_detailed:
            return calc_p_effective(
                p_dense=float(inp.params_dense or 0),
                p_moe=float(inp.params_moe or 0),
                n_experts=int(inp.n_experts or 1),
                k_experts=int(inp.k_experts or 1),
                bs_real=bs,
            )
        return p_active

    def _state_at_bs(bs_r: int) -> dict:
        """Per-instance throughput state at a given batch size (methodology §6.1–6.2)."""
        p_eff_local = _p_eff(bs_r)
        # Prefill at this BS
        if inp.th_prefill_empir:
            th_pf_mem_local = 0.0
            th_pf_local = float(inp.th_prefill_empir)
            pf_mode = "empirical"
        elif engine_mode == "continuous":
            th_pf_mem_local = calc_th_prefill_cb_mem(
                c_pf=int(inp.c_pf or 256),
                bw_gpu_gbs=bw_value,
                eta_mem=inp.eta_mem,
                p_effective_at_bs_plus_1=_p_eff(bs_r + 1),
                b_quant=inp.bytes_per_param,
                mkv_gb=MKV,
                bs_real=bs_r,
                o_fixed_gb=inp.o_fixed,
            )
            th_pf_local, pf_mode = select_th_prefill(th_pf_compute_branch, th_pf_mem_local)
        else:
            th_pf_mem_local = 0.0
            th_pf_local = th_pf_compute_branch
            pf_mode = "static"
        # Decode at this BS: compute branch per session, mem branch per session
        th_dec_cmp_session = th_dec_analyt / bs_r if bs_r > 0 else th_dec_analyt
        th_dec_mem_local = calc_th_decode_mem(
            bw_gpu_gbs=bw_value,
            eta_mem=inp.eta_mem,
            params_billions=p_eff_local,
            b_quant=inp.bytes_per_param,
            mkv_gb=MKV,
            bs_real=bs_r,
            o_fixed_gb=inp.o_fixed,
        )
        if inp.th_decode_empir:
            dec_sel = inp.th_decode_empir
            dec_mode = "empirical"
        else:
            dec_sel, dec_mode = select_th_decode(th_dec_cmp_session, th_dec_mem_local)
        th_dec_session = dec_sel * inp.k_spec
        cm = calc_Cmodel(SL_pf_eff, th_pf_local, Tdec, th_dec_session, bs_real=bs_r)
        return {
            "bs_real": bs_r,
            "p_effective": p_eff_local,
            "th_dec_compute_per_session": th_dec_cmp_session,
            "th_dec_mem": th_dec_mem_local,
            "th_dec": th_dec_session,
            "mode_decode_bound": dec_mode,
            "th_pf_compute": th_pf_compute_branch,
            "th_pf_mem": th_pf_mem_local,
            "th_pf": th_pf_local,
            "mode_prefill_bound": pf_mode,
            "cmodel": cm,
        }

    def _iteration_state(servers_in: int) -> dict:
        bs_r = calc_bs_real(Ssim, NcountTP, servers_in, bs_max=S_TP_z)
        st = _state_at_bs(bs_r)
        th_srv = calc_th_server_comp(NcountTP, st["cmodel"])
        sc = calc_servers_by_compute(Ssim, effective_R, inp.sla_reserve_KSLA, th_srv)
        if sc is math.inf:
            raise ValidationAppError(
                "Пропускная способность сервера = 0. "
                "Проверьте TFLOPS GPU, throughput или кол-во экземпляров на сервер."
            )
        st["th_server_comp"] = th_srv
        st["servers_comp"] = sc
        return st

    def _self_consistent(s: int) -> bool:
        return max(servers_mem, _iteration_state(s)["servers_comp"]) <= s

    trajectory = [servers_mem]
    iteration_status = "not_converged"
    servers_star = servers_mem
    iteration_count = 0
    for k in range(MAX_ITER):
        iteration_count = k + 1
        nxt = max(servers_mem, _iteration_state(trajectory[-1])["servers_comp"])
        if nxt == trajectory[-1]:
            iteration_status = "converged"
            servers_star = nxt
            break
        trajectory.append(nxt)
    else:
        candidate = max(trajectory[-1], trajectory[-2])
        if _self_consistent(candidate):
            iteration_status = "oscillating"
            servers_star = candidate
        else:
            # Smallest self-consistent S* ≥ candidate (methodology §6.4 Шаг 4.3).
            s = candidate
            while not _self_consistent(s) and s < candidate * 64 + 64:
                s += 1
            servers_star = s
            iteration_status = "not_converged"

    # ── §7.3 / §8: подбор числа серверов под SLA ──
    # Увеличение Servers снижает BS_real и задержку (§7.3). Перебираются
    # значения BS_real от текущего вниз до 1; принимается первое состояние,
    # в котором выполнены SLA и самосогласованность нагрузки (§6.4, q ≤ 1).
    state_bs1 = _state_at_bs(1)
    ttft_bs1 = calc_ttft(SL_pf_eff, state_bs1["th_pf"], state_bs1["th_dec"], inp.t_overhead)
    e2e_latency_analyt = calc_e2e_latency(ttft_bs1, calc_generation_time(Tdec, state_bs1["th_dec"]))

    def _latency(st: dict) -> tuple[float, float, float]:
        ttft = calc_ttft(SL_pf_eff, st["th_pf"], st["th_dec"], inp.t_overhead)
        e2e_call = max(e2e_latency_analyt, calc_e2e_latency_load(st["bs_real"], st["cmodel"]))
        return ttft, e2e_call, e2e_call * k_calls

    def _sla_ok(st: dict) -> bool:
        ttft, e2e_call, e2e_req = _latency(st)
        e2e = e2e_req if inp.e2e_sla_scope == "request" else e2e_call
        ok = True
        if inp.ttft_sla is not None:
            ok = ok and inp.ttft_sla >= ttft
        if inp.e2e_latency_sla is not None:
            ok = ok and inp.e2e_latency_sla >= e2e
        return ok

    servers_before_sla_fit = servers_star
    has_sla = inp.ttft_sla is not None or inp.e2e_latency_sla is not None
    if not has_sla:
        sla_fit_status = "not_required"
    elif not inp.sla_fit_servers:
        sla_fit_status = "disabled"
    else:
        st0 = _iteration_state(servers_star)
        sla_fit_status = "not_required"
        if not _sla_ok(st0):
            sla_fit_status = "unreachable"
            b = st0["bs_real"] - 1
            while b >= 1:
                s_b = max(servers_star, math.ceil(Ssim / (NcountTP * b)))
                st = _iteration_state(s_b)
                if st["bs_real"] <= b and _sla_ok(st) and _self_consistent(s_b):
                    servers_star = s_b
                    sla_fit_status = "fitted"
                    break
                b -= 1

    # Final single state at S*.
    state = _iteration_state(servers_star)

    BS_real = state["bs_real"]
    p_effective = state["p_effective"]
    th_dec_compute_per_session = state["th_dec_compute_per_session"]
    th_dec_mem = state["th_dec_mem"]
    th_dec = state["th_dec"]
    mode_decode_bound = state["mode_decode_bound"]
    th_pf_compute = state["th_pf_compute"]
    th_pf_mem = state["th_pf_mem"]
    th_pf = state["th_pf"]
    mode_prefill_bound = state["mode_prefill_bound"]
    Cmodel = state["cmodel"]
    th_server = state["th_server_comp"]
    # §6.4 Шаг 4: Servers^comp = comp(S*) when converged, S* otherwise, so
    # that max(Servers_mem, Servers_comp) = S*.
    servers_comp = (
        state["servers_comp"] if iteration_status == "converged" and sla_fit_status != "fitted" else servers_star
    )

    # §6.2: prefill utilisation diagnostic ρ_pf = C_model·SL_pf_eff / Th_pf
    rho_pf = Cmodel * SL_pf_eff / th_pf if th_pf > 0 else None

    # ── Section 7: TTFT and e2eLatency ──
    # SLA is checked at the final batch BS*; TTFT(1) / e2e_analyt are the
    # unloaded single-request lower bounds (informational).
    ttft_analyt = calc_ttft(SL_pf_eff, th_pf, th_dec, inp.t_overhead)
    gen_time_analyt = calc_generation_time(Tdec, th_dec)
    e2e_latency_load = max(e2e_latency_analyt, calc_e2e_latency_load(BS_real, Cmodel))
    e2e_latency_request = e2e_latency_load * k_calls
    e2e_latency_for_sla = e2e_latency_request if inp.e2e_sla_scope == "request" else e2e_latency_load
    # §6.4: самосогласованность нагрузки последовательной сессии
    session_load_q = effective_R * inp.sla_reserve_KSLA * e2e_latency_load
    session_consistent = session_load_q <= 1.0 + 1e-9

    ttft_sla_pass = None
    e2e_latency_sla_pass = None
    sla_passed = None

    if inp.ttft_sla is not None:
        ttft_sla_pass = inp.ttft_sla >= ttft_analyt
    if inp.e2e_latency_sla is not None:
        e2e_latency_sla_pass = inp.e2e_latency_sla >= e2e_latency_for_sla

    checks = [value for value in (ttft_sla_pass, e2e_latency_sla_pass) if value is not None]
    if checks:
        feasible = th_pf > 0 and th_dec > 0 and NcountTP > 0
        sla_passed = all(checks) and feasible

    # ── Appendix Б (Приложение Б): recommendations when SLA fails ──
    sla_recommendations = None
    if sla_passed is False:
        sla_recommendations = []
        ttft_fail = ttft_sla_pass is False
        e2e_fail = e2e_latency_sla_pass is False

        if ttft_fail and e2e_fail:
            sla_recommendations.extend(
                [
                    "1. Увеличить TP-множитель (Z) — штатный механизм, повышает Th_pf и Th_dec",
                    "2. Применить более агрессивную квантизацию (FP16→FP8/INT4)",
                    "5. Сменить на модель с меньшим числом параметров или MoE",
                    "6. Использовать более производительное оборудование (GPU с большей bandwidth)",
                ]
            )
        elif ttft_fail:
            sla_recommendations.extend(
                [
                    "3. Сократить длину контекста (SL): уменьшить системный промпт, глубину диалога, применить суммаризацию",
                    "1. Увеличить TP-множитель (Z) — повышает Th_pf",
                    "2. Применить более агрессивную квантизацию",
                ]
            )
        elif e2e_fail:
            sla_recommendations.extend(
                [
                    "4. Сократить объём генерации (T_out): ограничить max_tokens, уменьшить MRT",
                    "1. Увеличить TP-множитель (Z) — повышает Th_dec",
                    "2. Применить более агрессивную квантизацию",
                ]
            )

        sla_recommendations.append(
            "7. Пересмотреть целевые значения SLA, если техническая стоимость несоразмерна бизнес-ценности"
        )

    # ── Section Ж (P10): PD-disaggregation pool sizing ──
    # Methodology Ж.2: Servers_total = Servers_pf + Servers_dec, where each
    # pool is sized independently per §6 with its own dominant coefficient.
    # Per-pool eta overrides (pd_eta_pf_pool, pd_eta_mem_pool) reflect that
    # a phase-specialized pool may have different calibration coefficients
    # than a co-located deployment (§E.1.1 decode-heavy / §E.1.2 prefill-heavy).
    eta_pf_pool_used = (
        float(inp.pd_eta_pf_pool) if inp.pd_eta_pf_pool is not None else float(inp.eta_prefill)
    )
    eta_mem_pool_used = (
        float(inp.pd_eta_mem_pool) if inp.pd_eta_mem_pool is not None else float(inp.eta_mem)
    )

    # Pool-specific prefill throughput. Compute branch is linear in η_pf;
    # mem branch is independent of η_pf. Empirical override (when set) is a
    # measured value that bypasses analytical scaling.
    if inp.th_prefill_empir:
        th_pf_pool = float(inp.th_prefill_empir)
    else:
        pf_scale = eta_pf_pool_used / inp.eta_prefill if inp.eta_prefill > 0 else 1.0
        th_pf_compute_scaled = th_pf_compute * pf_scale if th_pf_compute > 0 else 0.0
        if engine_mode == "continuous" and th_pf_mem > 0 and th_pf_compute_scaled > 0:
            th_pf_pool = min(th_pf_compute_scaled, th_pf_mem)
        elif th_pf_compute_scaled > 0:
            th_pf_pool = th_pf_compute_scaled
        else:
            th_pf_pool = th_pf_mem if engine_mode == "continuous" else 0.0

    # Pool-specific decode per-session throughput. Mem branch is linear in
    # η_mem; compute branch (per session) is independent of η_mem.
    if inp.th_decode_empir:
        th_dec_session_pool = float(th_dec)
    else:
        mem_scale = eta_mem_pool_used / inp.eta_mem if inp.eta_mem > 0 else 1.0
        th_dec_mem_scaled = th_dec_mem * mem_scale if th_dec_mem > 0 else 0.0
        if th_dec_mem_scaled > 0 and th_dec_compute_per_session > 0:
            sel = min(th_dec_compute_per_session, th_dec_mem_scaled)
        elif th_dec_mem_scaled > 0:
            sel = th_dec_mem_scaled
        elif th_dec_compute_per_session > 0:
            sel = th_dec_compute_per_session
        else:
            sel = 0.0
        th_dec_session_pool = sel * inp.k_spec

    # Per-server pool throughput (req/sec).
    th_server_pf_val = calc_th_server_pf(NcountTP, th_pf_pool, SL_pf_eff)
    th_server_dec_val = calc_th_server_dec(NcountTP, th_dec_session_pool, BS_real, Tdec)

    # Per-pool server counts. Reuse §6.4 K_SLA framework with effective_R
    # (P8 amplification by K_calls).
    effective_R = inp.rps_per_session_R * k_calls
    servers_pf_count = calc_servers_by_compute(
        Ssim, effective_R, inp.sla_reserve_KSLA, th_server_pf_val
    )
    servers_dec_count = calc_servers_by_compute(
        Ssim, effective_R, inp.sla_reserve_KSLA, th_server_dec_val
    )

    if servers_pf_count is math.inf or servers_dec_count is math.inf:
        servers_pf_int = None
        servers_dec_int = None
        servers_pd_total = None
    else:
        servers_pf_int = int(servers_pf_count)
        servers_dec_int = int(servers_dec_count)
        servers_pd_total = servers_pf_int + servers_dec_int

    # Recommendation surface: when classical co-located sizing wastes >30%,
    # tell the operator that PD-disaggregation could save servers.
    pd_recommendation = None
    if (
        not inp.use_pd_disagg
        and servers_pd_total is not None
        and servers_comp not in (0, math.inf)
        and servers_pd_total < 0.7 * servers_comp
    ):
        savings_pct = round((1 - servers_pd_total / servers_comp) * 100)
        pd_recommendation = (
            f"PD-дизагрегация (Приложение Ж) могла бы сократить compute-серверы "
            f"на ~{savings_pct}% ({servers_comp} → {servers_pd_total}). "
            f"Установите use_pd_disagg=true для расчёта с раздельными пулами."
        )

    # ── Section 8: final server count ──
    if inp.use_pd_disagg and servers_pd_total is not None:
        servers_final = max(servers_mem, servers_pd_total)
    else:
        servers_final = max(servers_mem, servers_comp)

    # ── Cost estimate (from GPU catalog price: custom catalog or gpu_data.json) ──
    custom_catalog_list = None
    if getattr(inp, "custom_gpu_catalog", None) is not None:
        raw_catalog = inp.custom_gpu_catalog
        if isinstance(raw_catalog, list):
            custom_catalog_list = raw_catalog
        elif isinstance(raw_catalog, dict):
            custom_catalog_list = list(raw_catalog.values())

    price_per_gpu = lookup_gpu_price_usd(inp.gpu_id, inp.gpu_mem_gb, custom_catalog_list)
    cost_estimate_usd = (
        round(servers_final * inp.gpus_per_server * price_per_gpu, 2)
        if price_per_gpu is not None and price_per_gpu > 0
        else None
    )

    # ── Section 9: Gateway quotas (LiteLLM / shared vLLM rate-limits) ──
    # Pure demand-side: independent of GPU/server count. Values are conservative
    # upper bounds suitable for setting tpm/rpm caps on a shared vLLM pool.
    # See models.SizingOutput field docstrings for formula details.
    # Methodology §9: every LLM call (K_calls per user request) carries the
    # input SL_pf (conservative per-call peak) and generates T_dec tokens.
    user_request_rate_per_min = Ssim * inp.rps_per_session_R * inp.sla_reserve_KSLA * 60.0
    peak_rpm_val = user_request_rate_per_min * k_calls
    peak_tpm_input_val = peak_rpm_val * SL_pf
    peak_tpm_output_val = peak_rpm_val * Tdec
    peak_tpm_val = peak_tpm_input_val + peak_tpm_output_val
    k_sla = float(inp.sla_reserve_KSLA) if inp.sla_reserve_KSLA > 0 else 1.0
    sustained_rpm_val = peak_rpm_val / k_sla
    sustained_tpm_val = peak_tpm_val / k_sla
    max_parallel_requests_val = math.ceil(Ssim * k_sla)

    return SizingOutput(
        # Section 2
        Ssim_concurrent_sessions=Ssim,
        T_tokens_per_request=T,
        # Section 3
        model_mem_gb=Mmodel,
        TS_session_context=TS,
        SL_sequence_length=SL,
        kv_per_session_gb=MKV,
        kv_arch_mode=kv_arch_mode,
        # Section 4
        gpus_per_instance=GPUcount_model,
        instances_per_server=Ncount_model,
        kv_free_per_instance_gb=kv_free_base,
        S_TP_base=S_TP_base,
        S_TP_z=S_TP_z,
        Kbatch=Kbatch,
        instance_total_mem_gb=round(GPUcount_z * inp.gpu_mem_gb, 2),
        total_gpu_per_instance=GPUcount_model * Z_combined,
        total_gpu_count=servers_final * inp.gpus_per_server,
        eta_tp_used=eta_tp_used,
        pp_degree_used=pp_deg,
        ep_degree_used=ep_deg,
        kv_free_per_instance_tp_gb=round(kv_free_z, 4),
        # Section 5
        instances_per_server_tp=NcountTP,
        sessions_per_server=Sserver,
        servers_by_memory=servers_mem,
        # Section 6
        gpu_tflops_used=gpu_tflops,
        Fcount_model_tflops=gpu_tflops * GPUcount_z if gpu_tflops > 0 else 0.0,
        FPS_flops_per_token=FPS,
        p_active_used=p_active,
        p_effective_used=round(p_effective, 4),
        is_moe_detailed=is_moe_detailed,
        BS_real=BS_real,
        iteration_count=iteration_count,
        iteration_status=iteration_status,
        servers_trajectory=trajectory,
        rho_pf=round(rho_pf, 4) if rho_pf is not None else None,
        d_attn_prefill=d_attn_pf,
        d_attn_decode=d_attn_dec,
        SL_pf_raw=ctx.sl_pf_raw,
        context_truncated=ctx.truncated,
        ttft_bs1=round(ttft_bs1, 4) if ttft_bs1 != float("inf") else None,
        th_dec_compute_per_session_at_bs=round(th_dec_compute_per_session, 4)
        if th_dec_compute_per_session > 0
        else None,
        Tdec_tokens=Tdec,
        th_prefill=th_pf,
        th_pf_compute=round(th_pf_compute, 4) if th_pf_compute > 0 else None,
        th_pf_mem=round(th_pf_mem, 4) if th_pf_mem > 0 else None,
        mode_prefill_bound=mode_prefill_bound,
        th_decode=th_dec,
        th_dec_compute=round(th_dec_analyt, 4) if th_dec_analyt > 0 else None,
        th_dec_mem=round(th_dec_mem, 4) if th_dec_mem > 0 else None,
        mode_decode_bound=mode_decode_bound,
        bw_gpu_gbs_used=round(bw_gpu, 2) if bw_gpu else None,
        Cmodel_rps=Cmodel,
        th_server_comp=th_server,
        servers_by_compute=servers_comp,
        # Section Ж (P10): PD-disaggregation
        pd_disagg_used=bool(inp.use_pd_disagg),
        th_server_pf=round(th_server_pf_val, 4) if th_server_pf_val > 0 else None,
        th_server_dec=round(th_server_dec_val, 4) if th_server_dec_val > 0 else None,
        servers_pf=servers_pf_int,
        servers_dec=servers_dec_int,
        servers_pd_total=servers_pd_total,
        pd_eta_pf_pool_used=round(eta_pf_pool_used, 4),
        pd_eta_mem_pool_used=round(eta_mem_pool_used, 4),
        pd_recommendation=pd_recommendation,
        # Section 7: SLA validation
        SL_pf_input_length=SL_pf,
        SL_pf_eff_after_cache=round(SL_pf_eff, 4),
        ttft_analyt=round(ttft_analyt, 4) if ttft_analyt != float("inf") else None,
        generation_time_analyt=round(gen_time_analyt, 4)
        if gen_time_analyt != float("inf")
        else None,
        e2e_latency_analyt=round(e2e_latency_analyt, 4)
        if e2e_latency_analyt != float("inf")
        else None,
        e2e_latency_load=round(e2e_latency_load, 4) if e2e_latency_load != float("inf") else None,
        e2e_latency_for_sla=round(e2e_latency_for_sla, 4)
        if e2e_latency_for_sla != float("inf")
        else None,
        ttft_sla_target=inp.ttft_sla,
        e2e_latency_sla_target=inp.e2e_latency_sla,
        ttft_sla_pass=ttft_sla_pass,
        e2e_latency_sla_pass=e2e_latency_sla_pass,
        sla_passed=sla_passed,
        e2e_sla_scope=inp.e2e_sla_scope,
        e2e_latency_request=round(e2e_latency_request, 4),
        parallel_branches_P=inp.parallel_branches_P,
        session_load_q=round(session_load_q, 4),
        session_consistent=session_consistent,
        servers_before_sla_fit=servers_before_sla_fit,
        sla_fit_status=sla_fit_status,
        sizing_status=(
            "input_inconsistent" if not session_consistent else "sla_unreachable" if sla_fit_status == "unreachable" else "ok"
        ),
        sla_recommendations=sla_recommendations,
        # Section 8
        servers_final=servers_final,
        # Section 9: Gateway quotas
        peak_rpm=round(peak_rpm_val, 2),
        peak_tpm_input=round(peak_tpm_input_val, 2),
        peak_tpm_output=round(peak_tpm_output_val, 2),
        peak_tpm=round(peak_tpm_val, 2),
        sustained_rpm=round(sustained_rpm_val, 2),
        sustained_tpm=round(sustained_tpm_val, 2),
        max_parallel_requests=max_parallel_requests_val,
        # Context
        gpu_id=inp.gpu_id,
        gpu_mem_gb=inp.gpu_mem_gb,
        gpus_per_server=inp.gpus_per_server,
        cost_estimate_usd=cost_estimate_usd,
    )
