"""Workload normalization — single source for context lengths (methodology §2.2, Appendix В.3).

Every consumer (API sizing, Excel report, MCP) must derive token lengths
from :func:`normalize_context` so that the report and the API can never
diverge on how SP / Prp / RAG / tool add-ons are combined.

Context model (methodology §2.2, В.4а/В.4б/В.4)::

    m          = N_prp · K_calls                      # LLM calls per session
    SP_eff     = SP + SP_tools + C_rag_static
    Prp_eff    = Prp + C_rag_dynamic
    A_eff      = A + A_tool
    MRT_hist   = h_reason · MRT
    SL_pf_raw  = SP_eff + m·Prp_eff + (m − 1)·(A_eff + MRT_hist)   # input of the last call
    T_dec      = A_eff + MRT                                       # generated by one call
    TS         = SL_pf_raw + T_dec
    SL_pf      = min(SL_pf_raw, TS_max − T_dec)                    # window applied to input
    SL         = SL_pf + T_dec                                     # = min(TS, TS_max)
    SL_pf_eff  = SL_pf · (1 − η_cache)                             # recomputed prefill tokens

Attention width (methodology §6.1)::

    d_attn            = N_attn · d_head      (d_head defaults to H / N_attn)
    MLA prefill:      = N_attn · (2·d_head − d_rope) / 2
    MLA decode:       = N_attn · (2·r_kv + d_rope) / 2
"""

from __future__ import annotations

from dataclasses import asdict, dataclass

from errors import ValidationAppError


@dataclass(frozen=True)
class ContextLengths:
    k_calls: int
    total_calls: int
    sp_eff: float
    prp_eff: float
    a_eff: float
    mrt_hist: float
    sl_pf_raw: float
    t_dec: float
    ts: float
    sl_pf: float
    sl: float
    sl_pf_eff: float
    truncated: bool

    def as_dict(self) -> dict:
        return asdict(self)


def normalize_context(
    *,
    SP: float,
    Prp: float,
    MRT: float,
    A: float,
    n_prp: int,
    ts_max: float,
    k_calls: int | None = 1,
    sp_tools: float | None = 0.0,
    c_rag_static: float | None = 0.0,
    c_rag_dynamic: float | None = 0.0,
    a_tool: float | None = 0.0,
    reasoning_in_history: bool | float | None = False,
    eta_cache: float = 0.0,
) -> ContextLengths:
    """Return all context lengths for one session (see module docstring)."""
    k = int(k_calls or 1)
    m = int(n_prp) * k
    sp_eff = float(SP) + float(sp_tools or 0) + float(c_rag_static or 0)
    prp_eff = float(Prp) + float(c_rag_dynamic or 0)
    a_eff = float(A) + float(a_tool or 0)
    h = float(reasoning_in_history or 0)
    mrt_hist = h * float(MRT)

    sl_pf_raw = sp_eff + m * prp_eff + max(0, m - 1) * (a_eff + mrt_hist)
    t_dec = a_eff + float(MRT)
    ts = sl_pf_raw + t_dec
    if t_dec >= ts_max:
        raise ValidationAppError(
            "Генерация одного вызова (A + A_tool + MRT) не помещается в контекстное окно "
            f"модели: T_dec = {t_dec:.0f} ≥ TS_max = {ts_max:.0f}. "
            "Уменьшите MRT/A или выберите модель с большим окном."
        )
    sl_pf = min(sl_pf_raw, ts_max - t_dec)
    sl = sl_pf + t_dec
    return ContextLengths(
        k_calls=k,
        total_calls=m,
        sp_eff=sp_eff,
        prp_eff=prp_eff,
        a_eff=a_eff,
        mrt_hist=mrt_hist,
        sl_pf_raw=sl_pf_raw,
        t_dec=t_dec,
        ts=ts,
        sl_pf=sl_pf,
        sl=sl,
        sl_pf_eff=sl_pf * (1.0 - float(eta_cache or 0)),
        truncated=sl_pf < sl_pf_raw,
    )


def calc_d_attn(
    *,
    hidden_size: int,
    num_attention_heads: int,
    head_dim: int | None = None,
    kv_lora_rank: int | None = None,
    qk_rope_head_dim: int | None = None,
) -> tuple[float, float]:
    """Return (d_attn_prefill, d_attn_decode) per methodology §6.1.

    For MHA/GQA/MQA both phases use N_attn · d_head. For MLA (kv_lora_rank > 0)
    prefill runs over decompressed heads, decode over the absorbed latent.
    """
    n_attn = int(num_attention_heads)
    d_head = int(head_dim) if head_dim else (hidden_size / n_attn if n_attn else hidden_size)
    if kv_lora_rank and kv_lora_rank > 0:
        rope = int(qk_rope_head_dim or 0)
        d_pf = n_attn * (2 * d_head - rope) / 2
        d_dec = n_attn * (2 * int(kv_lora_rank) + rope) / 2
        return float(d_pf), float(d_dec)
    d = float(n_attn * d_head)
    return d, d
