"""Check backend coverage thresholds for overall and core-math scope."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def _percent(covered: int, total: int) -> float:
    if total <= 0:
        return 100.0
    return (covered / total) * 100.0


def _normalize(path: str) -> str:
    return path.replace("\\", "/")


def _read_coverage(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _aggregate_core(data: dict[str, Any], core_paths: list[str]) -> tuple[int, int, int, int]:
    files = data.get("files", {})
    expected = {_normalize(path) for path in core_paths}
    normalized_files = {_normalize(path): summary for path, summary in files.items()}

    missing = [path for path in sorted(expected) if path not in normalized_files]
    if missing:
        msg = ", ".join(missing)
        raise SystemExit(f"Core coverage paths not found in coverage.json: {msg}")

    covered_lines = 0
    num_statements = 0
    covered_branches = 0
    num_branches = 0

    for path in sorted(expected):
        summary = normalized_files[path]["summary"]
        covered_lines += int(summary.get("covered_lines", 0))
        num_statements += int(summary.get("num_statements", 0))
        covered_branches += int(summary.get("covered_branches", 0))
        num_branches += int(summary.get("num_branches", 0))

    return covered_lines, num_statements, covered_branches, num_branches


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--coverage-json",
        default="coverage.json",
        help="Path to coverage JSON report generated by `coverage json`.",
    )
    parser.add_argument("--overall-line", type=float, required=True)
    parser.add_argument("--overall-branch", type=float, required=True)
    parser.add_argument("--core-line", type=float, required=True)
    parser.add_argument("--core-branch", type=float, required=True)
    parser.add_argument(
        "--core-path",
        action="append",
        default=["core/sizing_math.py"],
        help="Core math file path relative to backend root. Can be passed multiple times.",
    )
    args = parser.parse_args()

    coverage_data = _read_coverage(Path(args.coverage_json))
    totals = coverage_data.get("totals", {})

    overall_line = _percent(int(totals.get("covered_lines", 0)), int(totals.get("num_statements", 0)))
    overall_branch = _percent(
        int(totals.get("covered_branches", 0)),
        int(totals.get("num_branches", 0)),
    )

    core_stats = _aggregate_core(coverage_data, args.core_path)
    core_line = _percent(core_stats[0], core_stats[1])
    core_branch = _percent(core_stats[2], core_stats[3])

    failures: list[str] = []
    if overall_line < args.overall_line:
        failures.append(
            f"overall line coverage {overall_line:.2f}% < required {args.overall_line:.2f}%"
        )
    if overall_branch < args.overall_branch:
        failures.append(
            f"overall branch coverage {overall_branch:.2f}% < required {args.overall_branch:.2f}%"
        )
    if core_line < args.core_line:
        failures.append(f"core line coverage {core_line:.2f}% < required {args.core_line:.2f}%")
    if core_branch < args.core_branch:
        failures.append(
            f"core branch coverage {core_branch:.2f}% < required {args.core_branch:.2f}%"
        )

    print(f"Overall line coverage:   {overall_line:.2f}%")
    print(f"Overall branch coverage: {overall_branch:.2f}%")
    print(f"Core line coverage:      {core_line:.2f}%")
    print(f"Core branch coverage:    {core_branch:.2f}%")

    if failures:
        for failure in failures:
            print(f"FAIL: {failure}")
        return 1

    print("Coverage thresholds satisfied.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
