def calc_tokens_per_request(P: float, A: float) -> float: ...
def calc_total_active(internal_users, p_in, c_in, external_users, p_ex, c_ex) -> float: ...
def calc_required_rps(total_active: float, R: float) -> float: ...
def calc_tokens_per_session(t: float, R: float, T: float) -> float: ...
def calc_model_mem_gb(params_b: float, bytes_per_param: float, overhead: float) -> float: ...
def calc_gpus_per_instance(model_mem_gb: float, gpu_mem_gb: float) -> int: ...
def calc_instances_per_server(gpus_per_server: int, gpus_per_instance: int) -> int: ...
def calc_kv_per_session_gb(L: int, H: int, TS: float, bytes_state: float, Kopt: float) -> float: ...
def calc_sessions_per_server(kv_per_session_gb: float, model_mem_gb: float,
                             gpus_per_instance: int, gpu_mem_gb: float,
                             instances_per_server: int, mem_reserve_fraction: float) -> int: ...
def calc_servers_by_memory(total_active: float, sessions_per_server: int) -> int: ...
def calc_rps_per_server(tps_per_instance: float, T: float,
                        instances_per_server: int, batching_coeff: float) -> float: ...
def calc_servers_by_compute(required_rps: float, rps_per_server: float, sla_reserve: float) -> int: ...
def calc_servers_final(servers_mem: int, servers_comp: int) -> int: ...
